# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gcya8Y4L6n7jQWlZCOuWSxZZ24aYYJnpFaHa63DaB9xCLyvVgPjJx3VNFhqxKz5AAp/1C8INqinCTxopWKie6/HKWNYibe4HCqiYjZcx/gAFpgvyprzduEg7+LGNGcuWWhe6n/V1s3c2UyvPfXA3xG/yf+CZhIXIvdGewD5ypd5fQY5KPfwU/G1F4CtNgoNjgDtmv/GMseyBTLr0NPfSbcmKkAyT+Wv4ge976Vj9T3ED6Uc9+qjdJfwUjMOf29zWx1u6DFEF4MMO66O32iCpP6NY/tNl6w80ChtbuqcyxBAobrzNgIEEdwR0s/Zh1EP92O9tx40UjkMaJoY+Kie474nVZomhvZUokoTpJy/1qaReGQ6gj3YCnh2aHY99nJ+63S+uYhFzN0+aW+vLzUfitG7IVmNTTCYfQ5WcTfYR+V5ryYkyx6cBY6jTGXgSuB7Vzh5Sdo/RTqtlq2src43KaKIZoqo3u/3gSC1QfeDtYeJwWjgo5Vt8H0vfVNR86gYeQriugBfhBJDi5GTBHEfscP1TJOpY0HmDmY1N00pUtjJUg3rJ1B1AcQhCi6Yx86g3H7Ia3z8+4aZ3vMXVd7gP85ttkNdLKeHsPyQky+BsVba7Q2SnftsjiJOa8bnsGkJZ+VIfdjWXsdUqOri0mKAKoywqqPXYfaQOGzRDo7rSL6M="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
