travis:
  secure:
    BINSTAR_TOKEN: O1J+9R30vgk5cSG+lXw263/GDlVaH2/hoiG5C+GhjjfZoXciTnqlv0P44iAuEFNYlfXUoYZnE62IK6ESBE0CGq36IBZ/k2vp/mZnIGtFgzmKQcAMvd2xGkeuCjtsJGp9XZyjFCdZd9l9K4ocZH2vad0is141kBr/afZo5ohsxr/BnCgpFEExgntAkmWUMPfM3+W0B/wg3G21ZhezjMRIj+m4QE+nSrso6FTrZdubk+Gk/bTG/Bo1Erg3pzpePwnjqCAYOtdBNEMimbBaRcdSu4KcFGHRaOWVXB7o05diAOwtH4Xg9JPp3zcu58ri4/Pn/Cd/pW99nZcEb82yqj/+EJkZkrdrcov9poF3o8iyxJl7LQEuBO+T3jzBi9PsPW8/Hmm1aARrUPScmax1uk5WSAaTsaermvsdmfw9g37QT681Sm8C0AIAVlXATGFxrPyVnJ0InER0RgzG6GsIy4HIdToczickTGwDMQp4bjxHEbYVDK8Vf1MiQYH8YnOTHEZJebe6bjIgcoY1Mj8Ioo1rTa5o08hK+FAzJ7qwaifIYj6eIXGAyrinH4B0Hs4UtKZNA1EKhxQn2oUnL7NwcTEFv3gyPvdkEqLFYRq7vO543IwGqsYjGT9GDmNL2aCkLJe8nL39HXVgcWG1MITI6eodfHkF6Y+lS6Oxq2+OYMjXdtA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
